# Generated by Django 5.2.15 on 2026-07-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBranchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('leader', 'Leader')], default='worker', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='warehouse.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'branch__code'],
                'indexes': [models.Index(fields=['user', 'branch'], name='accounts_us_user_id_0d0374_idx'), models.Index(fields=['branch', 'role'], name='accounts_us_branch__e7338e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='unique_user_branch_membership')],
            },
        ),
    ]
