from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from config.api import auth_login, auth_logout, auth_session, current_events, me_branch_memberships, router
from config.views import health_check
from operations.scanner_views import (
    InterBranchMMTasksView,
    ScannerCartWorkCurrentView,
    ScannerControlCartView,
    ScannerControlCartItemsView,
    ScannerControlFinishView,
    ScannerControlPrintLabelView,
    ScannerControlTargetView,
    ScannerContentsView,
    ScannerLocationContentsView,
    ScannerPickingPickView,
    ScannerPickingConfirmLocationView,
    ScannerPickingPrepareView,
    ScannerPickingScanView,
    ScannerProformasCreateJobsView,
    ScannerProformasView,
    ScannerProductLookupView,
    ScannerQuickTransferView,
    ScannerInterBranchArrivalView,
    ScannerReceivingCompleteView,
    ScannerReceivingCloseView,
    ScannerReceivingCurrentView,
    ScannerReceivingPutAwayView,
    ScannerReceivingScanProductView,
    ScannerReceivingStartView,
    ScannerSessionCurrentView,
    ScannerSessionEndView,
    ScannerSessionStartView,
    ScannerTaskStartView,
    ScannerTasksView,
)


urlpatterns = [
    path("api/health/", health_check, name="health-check"),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/auth/session/", auth_session, name="auth-session"),
    path("api/auth/login/", auth_login, name="auth-login"),
    path("api/auth/logout/", auth_logout, name="auth-logout"),
    path("api/me/branch-memberships/", me_branch_memberships, name="me-branch-memberships"),
    path("api/current-events/", current_events, name="current-events"),
    path("api/scanner/session/start/", ScannerSessionStartView.as_view(), name="scanner-session-start"),
    path("api/scanner/session/current/", ScannerSessionCurrentView.as_view(), name="scanner-session-current"),
    path("api/scanner/session/end/", ScannerSessionEndView.as_view(), name="scanner-session-end"),
    path("api/scanner/proformas/", ScannerProformasView.as_view(), name="scanner-proformas"),
    path("api/scanner/proformas/create-jobs/", ScannerProformasCreateJobsView.as_view(), name="scanner-proformas-create-jobs"),
    path("api/scanner/tasks/", ScannerTasksView.as_view(), name="scanner-tasks"),
    path("api/scanner/tasks/<int:job_id>/start/", ScannerTaskStartView.as_view(), name="scanner-task-start"),
    path("api/scanner/cart-work/current/", ScannerCartWorkCurrentView.as_view(), name="scanner-cart-work-current"),
    path("api/scanner/control/cart/", ScannerControlCartView.as_view(), name="scanner-control-cart"),
    path("api/scanner/picking/scan/", ScannerPickingScanView.as_view(), name="scanner-picking-scan"),
    path("api/scanner/picking/confirm-location/", ScannerPickingConfirmLocationView.as_view(), name="scanner-picking-confirm-location"),
    path("api/scanner/picking/pick/", ScannerPickingPickView.as_view(), name="scanner-picking-pick"),
    path("api/scanner/picking/prepare/", ScannerPickingPrepareView.as_view(), name="scanner-picking-prepare"),
    path("api/scanner/control/cart-items/", ScannerControlCartItemsView.as_view(), name="scanner-control-cart-items"),
    path("api/scanner/control/target/", ScannerControlTargetView.as_view(), name="scanner-control-target"),
    path("api/scanner/control/print-label/", ScannerControlPrintLabelView.as_view(), name="scanner-control-print-label"),
    path("api/scanner/control/finish/", ScannerControlFinishView.as_view(), name="scanner-control-finish"),
    path("api/scanner/contents/", ScannerContentsView.as_view(), name="scanner-contents"),
    path("api/scanner/products/lookup/", ScannerProductLookupView.as_view(), name="scanner-product-lookup"),
    path("api/scanner/locations/contents/", ScannerLocationContentsView.as_view(), name="scanner-location-contents"),
    path("api/scanner/quick-transfer/", ScannerQuickTransferView.as_view(), name="scanner-quick-transfer"),
    path("api/scanner/inter-branch-arrivals/", ScannerInterBranchArrivalView.as_view(), name="scanner-inter-branch-arrivals"),
    path("api/mm-tasks/", InterBranchMMTasksView.as_view(), name="inter-branch-mm-tasks"),
    path("api/scanner/receiving/start/", ScannerReceivingStartView.as_view(), name="scanner-receiving-start"),
    path("api/scanner/receiving/current/", ScannerReceivingCurrentView.as_view(), name="scanner-receiving-current"),
    path("api/scanner/receiving/scan-product/", ScannerReceivingScanProductView.as_view(), name="scanner-receiving-scan-product"),
    path("api/scanner/receiving/put-away/", ScannerReceivingPutAwayView.as_view(), name="scanner-receiving-put-away"),
    path("api/scanner/receiving/close/", ScannerReceivingCloseView.as_view(), name="scanner-receiving-close"),
    path("api/scanner/receiving/complete/", ScannerReceivingCompleteView.as_view(), name="scanner-receiving-complete"),
    path("api/", include(router.urls)),
    path("admin/", admin.site.urls),
]
