# Generated by Django 5.2.15 on 2026-06-18 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='warehouse_b_code_e515da_idx'), models.Index(fields=['is_active'], name='warehouse_b_is_acti_51aa56_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('location_type', models.CharField(choices=[('storage', 'Storage'), ('picking', 'Picking'), ('receiving', 'Receiving'), ('shipping', 'Shipping'), ('returns', 'Returns')], default='storage', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='warehouse.branch')),
            ],
            options={
                'ordering': ['branch__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('unit_of_measure', models.CharField(default='pcs', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sku'],
                'indexes': [models.Index(fields=['sku'], name='warehouse_p_sku_222eab_idx'), models.Index(fields=['barcode'], name='warehouse_p_barcode_40dbae_idx'), models.Index(fields=['is_active'], name='warehouse_p_is_acti_f643f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='warehouse.branch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='warehouse.product')),
            ],
            options={
                'ordering': ['branch__code', 'location__code', 'product__sku'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['branch', 'code'], name='warehouse_l_branch__62febc_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='warehouse_l_locatio_cb6e38_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active'], name='warehouse_l_is_acti_fa9569_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='unique_location_code_per_branch'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['branch'], name='warehouse_i_branch__9b6b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['location'], name='warehouse_i_locatio_42934f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product'], name='warehouse_i_product_abf845_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['branch', 'product'], name='warehouse_i_branch__aa321a_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('branch', 'location', 'product'), name='unique_inventory_product_per_location'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='inventory_quantity_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='inventory_quantity_reserved_non_negative'),
        ),
    ]
