# Generated by Django 5.2.15 on 2026-06-18 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_reference', models.CharField(max_length=128, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('allocated', 'Allocated'), ('picking', 'Picking'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='imported', max_length=32)),
                ('requested_ship_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='warehouse.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_picked', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='warehouse.product')),
            ],
            options={
                'ordering': ['order', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='PickingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('quantity_to_pick', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_picked', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_tasks', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_tasks', to='warehouse.branch')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_tasks', to='operations.orderline')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_tasks', to='warehouse.location')),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('put_away', 'Put away'), ('closed', 'Closed')], default='received', max_length=32)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_batches', to='warehouse.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('condition', models.CharField(choices=[('sellable', 'Sellable'), ('damaged', 'Damaged'), ('quarantine', 'Quarantine')], default='sellable', max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='warehouse.product')),
                ('return_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.returnbatch')),
            ],
            options={
                'ordering': ['return_batch', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('pick', 'Pick'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=32)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='warehouse.branch')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_movements', to='warehouse.location')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='warehouse.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='warehouse.product')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_stock_movements', to='warehouse.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status change'), ('system', 'System')], max_length=32)),
                ('entity_name', models.CharField(max_length=120)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='operations__action__6cad80_idx'), models.Index(fields=['entity_name', 'entity_id'], name='operations__entity__1a2b7b_idx'), models.Index(fields=['created_at'], name='operations__created_b10d6d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['external_reference'], name='operations__externa_8b832e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='operations__status_ba839e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__4e5473_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order'], name='operations__order_i_886e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['product'], name='operations__product_8db7b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_number'), name='unique_order_line_number'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_picked__gte', 0)), name='order_line_picked_non_negative'),
        ),
        migrations.AddIndex(
            model_name='pickingtask',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__8082ed_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingtask',
            index=models.Index(fields=['source_location'], name='operations__source__e4d254_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingtask',
            index=models.Index(fields=['assigned_to'], name='operations__assigne_a12827_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickingtask',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_to_pick__gt', 0)), name='picking_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='pickingtask',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_picked__gte', 0)), name='picking_picked_non_negative'),
        ),
        migrations.AddIndex(
            model_name='returnbatch',
            index=models.Index(fields=['reference'], name='operations__referen_a8e491_idx'),
        ),
        migrations.AddIndex(
            model_name='returnbatch',
            index=models.Index(fields=['status'], name='operations__status_b0d593_idx'),
        ),
        migrations.AddIndex(
            model_name='returnbatch',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__b52eca_idx'),
        ),
        migrations.AddIndex(
            model_name='returnline',
            index=models.Index(fields=['return_batch'], name='operations__return__434c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='returnline',
            index=models.Index(fields=['product'], name='operations__product_e042e7_idx'),
        ),
        migrations.AddIndex(
            model_name='returnline',
            index=models.Index(fields=['condition'], name='operations__conditi_0ea2b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.UniqueConstraint(fields=('return_batch', 'line_number'), name='unique_return_line_number'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='return_line_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', 'movement_type'], name='operations__branch__0760bd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product'], name='operations__product_d19c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='operations__referen_2c3d90_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='operations__created_c85db3_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'),
        ),
    ]
