# Generated by Django 5.2.15 on 2026-06-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_routes', to='warehouse.branch')),
            ],
            options={
                'ordering': ['branch__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RouteRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('run_number', models.PositiveIntegerField()),
                ('order_cutoff_time', models.TimeField()),
                ('sync_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('syncing', 'Syncing'), ('picking', 'Picking'), ('ready_to_close', 'Ready to close'), ('closed', 'Closed'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='operations.deliveryroute')),
            ],
            options={
                'ordering': ['service_date', 'route__code', 'run_number'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='route_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='operations.routerun'),
        ),
        migrations.AddIndex(
            model_name='deliveryroute',
            index=models.Index(fields=['branch', 'code'], name='operations__branch__e3a494_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryroute',
            index=models.Index(fields=['is_active'], name='operations__is_acti_a3f220_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryroute',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='unique_delivery_route_code_per_branch'),
        ),
        migrations.AddIndex(
            model_name='routerun',
            index=models.Index(fields=['route', 'service_date'], name='operations__route_i_562e78_idx'),
        ),
        migrations.AddIndex(
            model_name='routerun',
            index=models.Index(fields=['status'], name='operations__status_b59250_idx'),
        ),
        migrations.AddIndex(
            model_name='routerun',
            index=models.Index(fields=['service_date', 'departure_time'], name='operations__service_004d3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='routerun',
            constraint=models.UniqueConstraint(fields=('route', 'service_date', 'run_number'), name='unique_route_run_per_service_date'),
        ),
    ]
