# Generated by Django 5.2.15 on 2026-07-05 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_routerun_close_lifecycle'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_progress', 'In progress'), ('picked', 'Picked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=32)),
                ('mode', models.CharField(choices=[('merged', 'Merged'), ('separate', 'Separate')], max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickingJobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('control', 'Control'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='operations.scannercart')),
                ('confirmed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_cart_work_sessions', to='warehouse.location')),
                ('scanner_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_work_session', to='operations.scannersession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='cartpickeditem',
            name='cart_work_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picked_items', to='operations.cartworksession'),
        ),
        migrations.AddIndex(
            model_name='cartpickeditem',
            index=models.Index(fields=['cart_work_session', 'product'], name='operations__cart_wo_86b0ac_idx'),
        ),
        migrations.AddField(
            model_name='pickingjob',
            name='route_runs',
            field=models.ManyToManyField(related_name='picking_jobs', to='operations.routerun'),
        ),
        migrations.AddField(
            model_name='cartworksession',
            name='picking_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_work_sessions', to='operations.pickingjob'),
        ),
        migrations.AddField(
            model_name='pickingjobtask',
            name='picking_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='operations.pickingjob'),
        ),
        migrations.AddField(
            model_name='pickingjobtask',
            name='picking_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_task', to='operations.pickingtask'),
        ),
        migrations.AddField(
            model_name='pickingjob',
            name='tasks',
            field=models.ManyToManyField(related_name='picking_jobs', through='operations.PickingJobTask', to='operations.pickingtask'),
        ),
        migrations.AddIndex(
            model_name='cartworksession',
            index=models.Index(fields=['status'], name='operations__status_9a6898_idx'),
        ),
        migrations.AddIndex(
            model_name='cartworksession',
            index=models.Index(fields=['started_at'], name='operations__started_e7373a_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartworksession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'control'])), fields=('cart',), name='unique_active_cart_work_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='cartworksession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'control'])), fields=('picking_job',), name='unique_active_cart_work_per_job'),
        ),
        migrations.AddIndex(
            model_name='pickingjobtask',
            index=models.Index(fields=['picking_job'], name='operations__picking_ade4f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickingjobtask',
            constraint=models.UniqueConstraint(fields=('picking_job', 'picking_task'), name='unique_task_per_picking_job'),
        ),
        migrations.AddIndex(
            model_name='pickingjob',
            index=models.Index(fields=['status'], name='operations__status_953dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingjob',
            index=models.Index(fields=['mode'], name='operations__mode_fb6f12_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingjob',
            index=models.Index(fields=['started_at'], name='operations__started_79620c_idx'),
        ),
    ]
