# Generated by Django 5.2.15 on 2026-07-07 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_scannercustomerlabel_scan_code'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterBranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('in_transit', 'In transit'), ('receiving', 'Receiving'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='warehouse.branch')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='warehouse.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('in_transit', 'In transit'), ('receiving', 'Receiving'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='in_transit', max_length=32)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('receiving_started_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallets', to='operations.interbranchtransfer')),
            ],
            options={
                'ordering': ['scan_code'],
            },
        ),
        migrations.CreateModel(
            name='PalletReceivingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=32)),
                ('worker_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_sessions', to='operations.transferpallet')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PalletReceivingScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('worker_code', models.CharField(blank=True, max_length=64)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_receiving_scans', to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_receiving_scans', to='warehouse.product')),
                ('receiving_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='operations.palletreceivingsession')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_scans', to='operations.transferpallet')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferPalletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.transferpallet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_pallet_items', to='warehouse.product')),
            ],
            options={
                'ordering': ['product__sku'],
            },
        ),
        migrations.AddField(
            model_name='palletreceivingsession',
            name='current_pallet_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_receiving_sessions', to='operations.transferpalletitem'),
        ),
        migrations.AddIndex(
            model_name='interbranchtransfer',
            index=models.Index(fields=['reference'], name='operations__referen_40438f_idx'),
        ),
        migrations.AddIndex(
            model_name='interbranchtransfer',
            index=models.Index(fields=['status'], name='operations__status_e4968b_idx'),
        ),
        migrations.AddIndex(
            model_name='interbranchtransfer',
            index=models.Index(fields=['destination_branch', 'status'], name='operations__destina_db91f5_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpallet',
            index=models.Index(fields=['scan_code'], name='operations__scan_co_d5b457_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpallet',
            index=models.Index(fields=['status'], name='operations__status_5004c5_idx'),
        ),
        migrations.AddIndex(
            model_name='palletreceivingscan',
            index=models.Index(fields=['pallet'], name='operations__pallet__ad1828_idx'),
        ),
        migrations.AddIndex(
            model_name='palletreceivingscan',
            index=models.Index(fields=['product'], name='operations__product_889fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='palletreceivingscan',
            index=models.Index(fields=['destination_location'], name='operations__destina_2a48b3_idx'),
        ),
        migrations.AddIndex(
            model_name='palletreceivingscan',
            index=models.Index(fields=['scanned_at'], name='operations__scanned_e29b98_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpalletitem',
            index=models.Index(fields=['pallet'], name='operations__pallet__e78469_idx'),
        ),
        migrations.AddIndex(
            model_name='transferpalletitem',
            index=models.Index(fields=['product'], name='operations__product_cfe64c_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferpalletitem',
            constraint=models.UniqueConstraint(fields=('pallet', 'product'), name='unique_product_per_transfer_pallet'),
        ),
        migrations.AddConstraint(
            model_name='transferpalletitem',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gt', 0)), name='transfer_pallet_expected_positive'),
        ),
        migrations.AddConstraint(
            model_name='transferpalletitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='transfer_pallet_received_non_negative'),
        ),
        migrations.AddIndex(
            model_name='palletreceivingsession',
            index=models.Index(fields=['status'], name='operations__status_3445c4_idx'),
        ),
        migrations.AddIndex(
            model_name='palletreceivingsession',
            index=models.Index(fields=['started_at'], name='operations__started_e3b5c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='palletreceivingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('pallet',), name='unique_active_receiving_session_per_pallet'),
        ),
    ]
