# Generated by Django 5.2.15 on 2026-07-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_interbranchtransfer_transferpallet_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interbranchtransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('in_transit', 'In transit'), ('receiving', 'Receiving'), ('received', 'Received'), ('closed_with_discrepancy', 'Closed with discrepancy'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='transferpallet',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In transit'), ('receiving', 'Receiving'), ('received', 'Received'), ('closed_with_discrepancy', 'Closed with discrepancy'), ('cancelled', 'Cancelled')], default='in_transit', max_length=32),
        ),
        migrations.CreateModel(
            name='TransferDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('confirmed_shortage', 'Confirmed shortage')], default='open', max_length=32)),
                ('created_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('pallet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy', to='operations.transferpallet')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='operations.interbranchtransfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferDiscrepancyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discrepancy_type', models.CharField(choices=[('shortage', 'Shortage'), ('surplus', 'Surplus'), ('wrong_location', 'Wrong location')], max_length=32)),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('discrepancy_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.transferdiscrepancy')),
                ('pallet_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_items', to='operations.transferpalletitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_discrepancy_items', to='warehouse.product')),
            ],
            options={
                'ordering': ['product__sku'],
            },
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancy',
            index=models.Index(fields=['reference'], name='operations__referen_734886_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancy',
            index=models.Index(fields=['status'], name='operations__status_c67ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancy',
            index=models.Index(fields=['created_at'], name='operations__created_9cea04_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancyitem',
            index=models.Index(fields=['discrepancy'], name='operations__discrep_b466c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancyitem',
            index=models.Index(fields=['product'], name='operations__product_cf7ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancyitem',
            index=models.Index(fields=['discrepancy_type'], name='operations__discrep_446ca2_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferdiscrepancyitem',
            constraint=models.UniqueConstraint(fields=('discrepancy', 'pallet_item'), name='unique_discrepancy_item_per_pallet_item'),
        ),
        migrations.AddConstraint(
            model_name='transferdiscrepancyitem',
            constraint=models.CheckConstraint(condition=models.Q(('discrepancy_quantity__gt', 0)), name='transfer_discrepancy_quantity_positive'),
        ),
    ]
