# Generated by Django 5.2.15 on 2026-07-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_interbranchtransfer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdiscrepancy',
            name='last_report_printer_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transferdiscrepancy',
            name='report_print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferdiscrepancy',
            name='report_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancy',
            name='shortage_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancyitem',
            name='posted_to_unconfirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancyitem',
            name='posted_to_unconfirmed_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('pick', 'Pick'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('receiving_discrepancy', 'Receiving discrepancy')], max_length=32),
        ),
    ]
