# Generated by Django 5.2.15 on 2026-07-07 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_transferdiscrepancy_last_report_printer_code_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdiscrepancy',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancy',
            name='resolved_by_worker_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transferdiscrepancyitem',
            name='last_recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancyitem',
            name='recovered_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('pick', 'Pick'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('receiving_discrepancy', 'Receiving discrepancy'), ('discrepancy_recovery', 'Discrepancy recovery')], max_length=32),
        ),
        migrations.CreateModel(
            name='TransferDiscrepancyRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('worker_code', models.CharField(blank=True, max_length=64)),
                ('recovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_operation_id', models.CharField(max_length=128, unique=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_recovery_destinations', to='warehouse.location')),
                ('discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='operations.transferdiscrepancy')),
                ('discrepancy_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='operations.transferdiscrepancyitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_discrepancy_recoveries', to='warehouse.product')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_recovery_sources', to='warehouse.location')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_recoveries', to='operations.stockmovement')),
            ],
            options={
                'ordering': ['-recovered_at'],
                'indexes': [models.Index(fields=['discrepancy'], name='operations__discrep_20fd59_idx'), models.Index(fields=['discrepancy_item'], name='operations__discrep_c753c0_idx'), models.Index(fields=['product'], name='operations__product_eb1d4f_idx'), models.Index(fields=['client_operation_id'], name='operations__client__595c4a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_discrepancy_recovery_quantity_positive')],
            },
        ),
    ]
