# Generated by Django 5.2.15 on 2026-07-07 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_transferdiscrepancy_resolved_at_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdiscrepancy',
            name='confirmed_shortage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancy',
            name='confirmed_shortage_by_worker_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transferdiscrepancyitem',
            name='confirmed_shortage_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transferdiscrepancyitem',
            name='last_confirmed_shortage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('pick', 'Pick'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('receiving_discrepancy', 'Receiving discrepancy'), ('discrepancy_recovery', 'Discrepancy recovery'), ('discrepancy_shortage', 'Discrepancy shortage')], max_length=32),
        ),
        migrations.CreateModel(
            name='TransferDiscrepancyShortageConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('worker_code', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_operation_id', models.CharField(max_length=128, unique=True)),
                ('discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shortage_confirmations', to='operations.transferdiscrepancy')),
                ('discrepancy_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shortage_confirmations', to='operations.transferdiscrepancyitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_discrepancy_shortage_confirmations', to='warehouse.product')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_shortage_confirmations', to='operations.stockmovement')),
                ('unconfirmed_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_shortage_confirmations', to='warehouse.location')),
            ],
            options={
                'ordering': ['-confirmed_at'],
                'indexes': [models.Index(fields=['discrepancy'], name='operations__discrep_4a6681_idx'), models.Index(fields=['discrepancy_item'], name='operations__discrep_b5bf77_idx'), models.Index(fields=['product'], name='operations__product_962973_idx'), models.Index(fields=['client_operation_id'], name='operations__client__6c9a48_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_discrepancy_shortage_confirmation_quantity_positive')],
            },
        ),
    ]
