# Generated by Django 5.2.15 on 2026-07-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_transferdiscrepancy_confirmed_shortage_at_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDiscrepancySourceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('investigating', 'Investigating'), ('completed', 'Completed')], default='pending_review', max_length=32)),
                ('finding', models.CharField(blank=True, choices=[('source_shortage_found', 'Source shortage found'), ('dispatch_evidence_matches', 'Dispatch evidence matches expected quantity'), ('inconclusive', 'Inconclusive')], max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('started_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('finding_note', models.TextField(blank=True)),
                ('client_operation_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('discrepancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source_review', to='operations.transferdiscrepancy')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_discrepancy_source_reviews', to='warehouse.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='operations__referen_d84c92_idx'), models.Index(fields=['status'], name='operations__status_2a6630_idx'), models.Index(fields=['source_branch', 'status'], name='operations__source__48380b_idx'), models.Index(fields=['client_operation_id'], name='operations__client__4c758f_idx')],
            },
        ),
    ]
