# Generated by Django 5.2.15 on 2026-07-07 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_transferdiscrepancysourcereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDiscrepancyReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('route', models.CharField(choices=[('source_stock_verification', 'Source stock verification required'), ('transit_investigation', 'Transit investigation required'), ('manual_reconciliation', 'Manual reconciliation required')], max_length=64)),
                ('status', models.CharField(choices=[('pending_action', 'Pending action'), ('in_progress', 'In progress')], default='pending_action', max_length=32)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('discrepancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='operations.transferdiscrepancy')),
                ('source_review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='operations.transferdiscrepancysourcereview')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='operations__referen_89e7be_idx'), models.Index(fields=['route'], name='operations__route_d2effc_idx'), models.Index(fields=['status'], name='operations__status_43cc5f_idx'), models.Index(fields=['route', 'status'], name='operations__route_dedad8_idx')],
            },
        ),
    ]
