# Generated by Django 5.2.15 on 2026-07-08 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_transferdiscrepancyreconciliation'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdiscrepancyreconciliation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancyreconciliation',
            name='completed_by_worker_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('pick', 'Pick'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('receiving_discrepancy', 'Receiving discrepancy'), ('discrepancy_recovery', 'Discrepancy recovery'), ('discrepancy_shortage', 'Discrepancy shortage'), ('source_discrepancy_recovery', 'Source discrepancy recovery')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transferdiscrepancyreconciliation',
            name='status',
            field=models.CharField(choices=[('pending_action', 'Pending action'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='pending_action', max_length=32),
        ),
        migrations.CreateModel(
            name='TransferDiscrepancySourceStockVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('investigating', 'Investigating'), ('completed', 'Completed')], default='pending_verification', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('started_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('reconciliation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_verification', to='operations.transferdiscrepancyreconciliation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferDiscrepancySourceStockVerificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('found_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('last_found_at', models.DateTimeField(blank=True, null=True)),
                ('discrepancy_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_verification_items', to='operations.transferdiscrepancyitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_verification_items', to='warehouse.product')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.transferdiscrepancysourcestockverification')),
            ],
            options={
                'ordering': ['product__sku'],
            },
        ),
        migrations.CreateModel(
            name='TransferDiscrepancySourceStockRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('worker_code', models.CharField(blank=True, max_length=64)),
                ('recovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_operation_id', models.CharField(max_length=128, unique=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_recoveries', to='warehouse.location')),
                ('discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_recoveries', to='operations.transferdiscrepancy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_recoveries', to='warehouse.product')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_recoveries', to='operations.stockmovement')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='operations.transferdiscrepancysourcestockverification')),
                ('verification_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='operations.transferdiscrepancysourcestockverificationitem')),
            ],
            options={
                'ordering': ['-recovered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockverification',
            index=models.Index(fields=['reference'], name='operations__referen_85e236_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockverification',
            index=models.Index(fields=['status'], name='operations__status_1cceee_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockverification',
            index=models.Index(fields=['created_at'], name='operations__created_65d111_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockverificationitem',
            index=models.Index(fields=['verification'], name='operations__verific_9db410_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockverificationitem',
            index=models.Index(fields=['product'], name='operations__product_418f92_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferdiscrepancysourcestockverificationitem',
            constraint=models.UniqueConstraint(fields=('verification', 'discrepancy_item'), name='unique_source_stock_verification_item_per_discrepancy_item'),
        ),
        migrations.AddConstraint(
            model_name='transferdiscrepancysourcestockverificationitem',
            constraint=models.CheckConstraint(condition=models.Q(('target_quantity__gt', 0)), name='source_stock_verification_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='transferdiscrepancysourcestockverificationitem',
            constraint=models.CheckConstraint(condition=models.Q(('found_quantity__gte', 0)), name='source_stock_verification_found_non_negative'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockrecovery',
            index=models.Index(fields=['verification'], name='operations__verific_a04fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockrecovery',
            index=models.Index(fields=['verification_item'], name='operations__verific_e399d6_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockrecovery',
            index=models.Index(fields=['discrepancy'], name='operations__discrep_066ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockrecovery',
            index=models.Index(fields=['product'], name='operations__product_9e24a2_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockrecovery',
            index=models.Index(fields=['client_operation_id'], name='operations__client__445af3_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferdiscrepancysourcestockrecovery',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='source_stock_recovery_quantity_positive'),
        ),
    ]
