# Generated by Django 5.2.15 on 2026-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_transferdiscrepancyreconciliation_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdiscrepancysourcestockverification',
            name='search_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancysourcestockverification',
            name='search_completed_by_worker_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transferdiscrepancysourcestockverification',
            name='search_completion_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferdiscrepancysourcestockverification',
            name='search_completion_operation_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transferdiscrepancyreconciliation',
            name='status',
            field=models.CharField(choices=[('pending_action', 'Pending action'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('manual_action_required', 'Manual action required')], default='pending_action', max_length=32),
        ),
        migrations.AlterField(
            model_name='transferdiscrepancysourcestockverification',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending verification'), ('investigating', 'Investigating'), ('completed', 'Completed'), ('completed_unresolved', 'Completed with unresolved stock')], default='pending_verification', max_length=32),
        ),
        migrations.AddIndex(
            model_name='transferdiscrepancysourcestockverification',
            index=models.Index(fields=['search_completion_operation_id'], name='operations__search__f13414_idx'),
        ),
    ]
