# Generated by Django 5.2.15 on 2026-07-08 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_transferdiscrepancysourcestockverification_search_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDiscrepancyManualReconciliationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('source_loss_confirmed', 'Source loss confirmed'), ('unresolved_loss_closed', 'Unresolved loss - cause not determined'), ('administrative_error', 'Administrative or process error')], max_length=64)),
                ('decision_note', models.TextField()),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by_worker_code', models.CharField(max_length=64)),
                ('client_operation_id', models.CharField(max_length=128, unique=True)),
                ('reconciliation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_decision', to='operations.transferdiscrepancyreconciliation')),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['outcome'], name='operations__outcome_6b9e20_idx'), models.Index(fields=['decided_at'], name='operations__decided_39a1bc_idx'), models.Index(fields=['client_operation_id'], name='operations__client__7622af_idx')],
            },
        ),
    ]
