# Generated by Django 5.2.15 on 2026-07-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_transferdiscrepancymanualreconciliationdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDiscrepancyTransitInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending_investigation', 'Pending investigation'), ('investigating', 'Investigating'), ('completed', 'Completed')], default='pending_investigation', max_length=32)),
                ('finding', models.CharField(blank=True, choices=[('transit_irregularity_found', 'Transit irregularity found'), ('no_transit_irregularity_identified', 'No transit irregularity identified'), ('inconclusive', 'Inconclusive')], max_length=64)),
                ('finding_note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('started_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('completion_operation_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('reconciliation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transit_investigation', to='operations.transferdiscrepancyreconciliation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='operations__referen_728691_idx'), models.Index(fields=['status'], name='operations__status_4fdcf6_idx'), models.Index(fields=['finding'], name='operations__finding_91ab9c_idx'), models.Index(fields=['completion_operation_id'], name='operations__complet_064127_idx')],
            },
        ),
    ]
