# Generated by Django 5.2.15 on 2026-07-10 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_alter_transferdiscrepancymanualreconciliationdecision_outcome'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='warehouse.branch'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='operations.scannercart'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='destination_label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_audit_logs', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='discrepancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='operations.transferdiscrepancy'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='operations.order'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='operations.transferpallet'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='warehouse.product'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='result',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='route_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='operations.routerun'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source_label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_audit_logs', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='operations.interbranchtransfer'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='operations__event_t_97f351_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['branch', 'event_type'], name='operations__branch__5430fa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['product'], name='operations__product_6a3e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['cart'], name='operations__cart_id_39fabf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['order'], name='operations__order_i_73028a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['route_run'], name='operations__route_r_c0dfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['transfer'], name='operations__transfe_81255e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['pallet'], name='operations__pallet__622ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['reference'], name='operations__referen_8fb247_idx'),
        ),
    ]
