# Generated by Django 5.2.15 on 2026-07-13 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_transferpalletarrival'),
        ('warehouse', '0002_product_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('recovered_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('confirmed_missing_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('customer_alias_snapshot', models.CharField(blank=True, max_length=128)),
                ('reported_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Open - awaiting later stock search'), ('found', 'Found'), ('confirmed_missing', 'Confirmed missing')], default='open', max_length=32)),
                ('confirmation_nonce', models.CharField(max_length=128, unique=True)),
                ('client_operation_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('found_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('found_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_missing_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('confirmed_missing_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('customer_alias', models.CharField(max_length=128)),
                ('order_reference', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('picking_shortage', 'Picking shortage')], default='picking_shortage', max_length=32)),
                ('status', models.CharField(choices=[('pending_order', 'Pending order'), ('ordered_manually', 'Ordered manually'), ('exported_to_ax', 'Exported to AX'), ('cancelled', 'Cancelled')], default='pending_order', max_length=32)),
                ('external_system', models.CharField(default='AX', max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('ordered_by_worker_code', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer_alias',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='pickingtask',
            name='shortage_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pickingtask',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('picked', 'Picked'), ('waiting_replenishment', 'Waiting for replenishment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('pick', 'Pick'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('receiving_discrepancy', 'Receiving discrepancy'), ('discrepancy_recovery', 'Discrepancy recovery'), ('discrepancy_shortage', 'Discrepancy shortage'), ('source_discrepancy_recovery', 'Source discrepancy recovery'), ('picking_shortage', 'Picking shortage'), ('picking_shortage_found', 'Picking shortage found'), ('picking_shortage_confirmed_missing', 'Picking shortage confirmed missing')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='pickingtask',
            constraint=models.CheckConstraint(condition=models.Q(('shortage_quantity__gte', 0)), name='picking_shortage_non_negative'),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_shortages', to='warehouse.branch'),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_shortages', to='operations.scannercart'),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='confirmed_missing_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_missing_picking_shortages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='found_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_picking_shortages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='found_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_picking_shortages', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_shortages', to='operations.order'),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='picking_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shortages', to='operations.pickingtask'),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_shortages', to='warehouse.product'),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_picking_shortages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='reported_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_picking_shortages', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='unconfirmed_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unconfirmed_picking_shortages', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='replenishmentrequest',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_requests', to='warehouse.branch'),
        ),
        migrations.AddField(
            model_name='replenishmentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_replenishment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replenishmentrequest',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_replenishment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replenishmentrequest',
            name='picking_shortage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_request', to='operations.pickingshortage'),
        ),
        migrations.AddField(
            model_name='replenishmentrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_requests', to='warehouse.product'),
        ),
        migrations.AddIndex(
            model_name='pickingshortage',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__4b3d52_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingshortage',
            index=models.Index(fields=['product'], name='operations__product_b2efdc_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingshortage',
            index=models.Index(fields=['reported_location'], name='operations__reporte_b426c7_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingshortage',
            index=models.Index(fields=['reported_at'], name='operations__reporte_414f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingshortage',
            index=models.Index(fields=['reference'], name='operations__referen_2b3bfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickingshortage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='picking_shortage_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='pickingshortage',
            constraint=models.CheckConstraint(condition=models.Q(('recovered_quantity__gte', 0)), name='picking_shortage_recovered_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='pickingshortage',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_missing_quantity__gte', 0)), name='picking_shortage_confirmed_missing_non_negative'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__b4fcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['product'], name='operations__product_ca35d0_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['customer_alias'], name='operations__custome_a9760b_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['order_reference'], name='operations__order_r_fc7735_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentrequest',
            index=models.Index(fields=['reference'], name='operations__referen_54140a_idx'),
        ),
        migrations.AddConstraint(
            model_name='replenishmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='replenishment_request_quantity_positive'),
        ),
    ]
