# Generated by Django 5.2.15 on 2026-07-14 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_pickingshortage_replenishmentrequest_and_more'),
        ('warehouse', '0002_product_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingShortageAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('picked_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('picking', 'Picking'), ('completed', 'Completed'), ('released', 'Released')], default='allocated', max_length=32)),
            ],
            options={
                'ordering': ['source_location__code', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='alternative_allocated_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pickingshortage',
            name='customer_unfulfilled_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='pickingshortage',
            constraint=models.CheckConstraint(condition=models.Q(('alternative_allocated_quantity__gte', 0)), name='picking_shortage_alternative_allocated_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='pickingshortage',
            constraint=models.CheckConstraint(condition=models.Q(('customer_unfulfilled_quantity__gte', 0)), name='picking_shortage_customer_unfulfilled_non_negative'),
        ),
        migrations.AddField(
            model_name='pickingshortageallocation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_shortage_allocations', to='warehouse.branch'),
        ),
        migrations.AddField(
            model_name='pickingshortageallocation',
            name='original_picking_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shortage_original_allocations', to='operations.pickingtask'),
        ),
        migrations.AddField(
            model_name='pickingshortageallocation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_shortage_allocations', to='warehouse.product'),
        ),
        migrations.AddField(
            model_name='pickingshortageallocation',
            name='replacement_picking_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shortage_replacement_allocation', to='operations.pickingtask'),
        ),
        migrations.AddField(
            model_name='pickingshortageallocation',
            name='shortage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='operations.pickingshortage'),
        ),
        migrations.AddField(
            model_name='pickingshortageallocation',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_shortage_allocations', to='warehouse.location'),
        ),
        migrations.AddIndex(
            model_name='pickingshortageallocation',
            index=models.Index(fields=['shortage'], name='operations__shortag_8dbb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingshortageallocation',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__c17542_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingshortageallocation',
            index=models.Index(fields=['product'], name='operations__product_657f95_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingshortageallocation',
            index=models.Index(fields=['source_location'], name='operations__source__f4cbf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickingshortageallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='picking_shortage_allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='pickingshortageallocation',
            constraint=models.CheckConstraint(condition=models.Q(('picked_quantity__gte', 0)), name='picking_shortage_allocation_picked_non_negative'),
        ),
    ]
