# Generated by Django 5.2.15 on 2026-07-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_pickingshortageallocation_and_more'),
        ('warehouse', '0002_product_presentation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentrequest',
            name='picking_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_requests', to='operations.pickingtask'),
        ),
        migrations.AlterField(
            model_name='replenishmentrequest',
            name='picking_shortage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_request', to='operations.pickingshortage'),
        ),
        migrations.AlterField(
            model_name='replenishmentrequest',
            name='reason',
            field=models.CharField(choices=[('picking_shortage', 'Picking shortage'), ('system_stock_unavailable', 'System stock unavailable')], default='picking_shortage', max_length=32),
        ),
        migrations.CreateModel(
            name='PickingTaskReallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('system_stock_unavailable', 'System stock unavailable')], default='system_stock_unavailable', max_length=64)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_task_reallocations', to='warehouse.branch')),
                ('original_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_picking_task_reallocations', to='warehouse.location')),
                ('original_picking_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_reallocations', to='operations.pickingtask')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_task_reallocations', to='warehouse.product')),
                ('replacement_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_picking_task_reallocations', to='warehouse.location')),
                ('replacement_picking_task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='system_reallocation_source', to='operations.pickingtask')),
            ],
            options={
                'ordering': ['replacement_location__code', 'created_at'],
                'indexes': [models.Index(fields=['original_picking_task'], name='operations__origina_58b50e_idx'), models.Index(fields=['replacement_picking_task'], name='operations__replace_a84eee_idx'), models.Index(fields=['branch', 'product'], name='operations__branch__5d89f7_idx'), models.Index(fields=['original_location'], name='operations__origina_0a08af_idx'), models.Index(fields=['replacement_location'], name='operations__replace_a1ddd6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='picking_task_reallocation_quantity_positive')],
            },
        ),
    ]
