# Generated by Django 5.2.16 on 2026-07-14 14:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_replenishmentrequest_picking_task_and_more'),
        ('warehouse', '0002_product_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartWorkParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left')], default='active', max_length=32)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('current_task_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_work_participants', to='warehouse.branch')),
                ('cart_work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='operations.cartworksession')),
                ('confirmed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participant_confirmed_cart_work', to='warehouse.location')),
                ('current_picking_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_cart_work_participants', to='operations.pickingtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_work_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PickingTaskClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('released', 'Released'), ('completed', 'Completed')], default='claimed', max_length=32)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cart_work_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_claims', to='operations.cartworkparticipant')),
                ('picking_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_claims', to='operations.pickingtask')),
            ],
            options={
                'ordering': ['-claimed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cartworkparticipant',
            index=models.Index(fields=['cart_work_session', 'status'], name='operations__cart_wo_aaf7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartworkparticipant',
            index=models.Index(fields=['user', 'status'], name='operations__user_id_770bff_idx'),
        ),
        migrations.AddIndex(
            model_name='cartworkparticipant',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__5e7a55_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartworkparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('cart_work_session', 'user'), name='unique_active_participant_per_cart_work_user'),
        ),
        migrations.AddConstraint(
            model_name='cartworkparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_cart_work_participant_per_user'),
        ),
        migrations.AddIndex(
            model_name='pickingtaskclaim',
            index=models.Index(fields=['picking_task', 'status'], name='operations__picking_3cb65c_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingtaskclaim',
            index=models.Index(fields=['cart_work_participant', 'status'], name='operations__cart_wo_6bf501_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickingtaskclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'claimed')), fields=('picking_task',), name='unique_active_claim_per_picking_task'),
        ),
        migrations.AddConstraint(
            model_name='pickingtaskclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'claimed')), fields=('cart_work_participant',), name='unique_active_claim_per_participant'),
        ),
    ]
