# Generated by Django 5.2.16 on 2026-07-15 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_cartworkparticipant_pickingtaskclaim_and_more'),
        ('warehouse', '0002_product_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartworkparticipant',
            name='picking_direction',
            field=models.CharField(choices=[('beginning', 'Beginning'), ('end', 'End'), ('manual', 'Manual selection')], default='beginning', max_length=32),
        ),
        migrations.AddField(
            model_name='cartworkparticipant',
            name='work_state',
            field=models.CharField(choices=[('active', 'Active'), ('waiting_for_available_line', 'Waiting for available line'), ('completed_participation', 'Completed participation')], default='active', max_length=64),
        ),
        migrations.AddIndex(
            model_name='cartworkparticipant',
            index=models.Index(fields=['picking_direction'], name='operations__picking_020d70_idx'),
        ),
        migrations.AddIndex(
            model_name='cartworkparticipant',
            index=models.Index(fields=['work_state'], name='operations__work_st_946023_idx'),
        ),
    ]
