# Generated by Django 5.2.16 on 2026-07-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_cartworkparticipant_picking_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='adjustment_direction',
            field=models.CharField(blank=True, choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=16),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='adjustment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('count_correction', 'Count correction'), ('damaged_stock', 'Damaged stock'), ('found_stock', 'Found stock'), ('data_entry_correction', 'Data entry correction'), ('other', 'Other')], max_length=64),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
