# Generated by Django 5.2.16 on 2026-07-17 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_stockmovement_adjustment_direction_and_more'),
        ('warehouse', '0002_product_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In progress'), ('awaiting_review', 'Awaiting review'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_sessions', to='warehouse.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_cycle_count_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycle_count_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_cycle_count_sessions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cycle_count_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_locations', to='warehouse.branch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_locations', to='warehouse.location')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_cycle_count_locations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cycle_count_locations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='operations.cyclecountsession')),
            ],
            options={
                'ordering': ['location__code'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('is_expected', models.BooleanField(default=True)),
                ('movement_after_snapshot', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='warehouse.branch')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_cycle_count_lines', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='warehouse.product')),
                ('cycle_count_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.cyclecountlocation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.cyclecountsession')),
            ],
            options={
                'ordering': ['location__code', 'product__sku'],
            },
        ),
        migrations.AddIndex(
            model_name='cyclecountsession',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__593799_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountsession',
            index=models.Index(fields=['reference'], name='operations__referen_be1316_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountsession',
            index=models.Index(fields=['created_at'], name='operations__created_731c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountlocation',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__9e1a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountlocation',
            index=models.Index(fields=['session', 'status'], name='operations__session_349ae0_idx'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountlocation',
            constraint=models.UniqueConstraint(fields=('session', 'location'), name='unique_cycle_count_location_per_session'),
        ),
        migrations.AddIndex(
            model_name='cyclecountline',
            index=models.Index(fields=['session', 'location'], name='operations__session_b3f9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountline',
            index=models.Index(fields=['branch', 'product'], name='operations__branch__0f1e01_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountline',
            index=models.Index(fields=['movement_after_snapshot'], name='operations__movemen_8ef20f_idx'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountline',
            constraint=models.UniqueConstraint(fields=('cycle_count_location', 'product'), name='unique_cycle_count_line_product_per_location'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gte', 0)), name='cycle_count_expected_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__gte', 0), ('counted_quantity__isnull', True), _connector='OR'), name='cycle_count_counted_non_negative'),
        ),
    ]
