# Generated by Django 5.2.16 on 2026-07-17 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_cyclecountsession_cyclecountlocation_cyclecountline_and_more'),
        ('warehouse', '0002_product_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclecountline',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_cycle_count_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='reconciliation_status',
            field=models.CharField(blank=True, choices=[('no_variance', 'No variance'), ('pending_review', 'Pending review'), ('adjustment_applied', 'Adjustment applied'), ('no_adjustment_required', 'No adjustment required')], max_length=32),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='cycle_count_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_stock_movement', to='operations.cyclecountline'),
        ),
        migrations.AddIndex(
            model_name='cyclecountline',
            index=models.Index(fields=['reconciliation_status'], name='operations__reconci_653f0b_idx'),
        ),
    ]
