# Generated by Django 5.2.16 on 2026-07-17 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_cyclecountline_reconciled_at_and_more'),
        ('warehouse', '0002_product_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCountRecount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('baseline_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('movement_after_baseline', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_cycle_count_recounts', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_recounts', to='warehouse.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_cycle_count_recounts', to=settings.AUTH_USER_MODEL)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_cycle_count_recounts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_recounts', to='warehouse.location')),
                ('original_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recounts', to='operations.cyclecountline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_recounts', to='warehouse.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_cycle_count_recounts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recounts', to='operations.cyclecountsession')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_cycle_count_recounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='cycle_count_recount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_stock_movement', to='operations.cyclecountrecount'),
        ),
        migrations.AddIndex(
            model_name='cyclecountrecount',
            index=models.Index(fields=['branch', 'status'], name='operations__branch__443c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountrecount',
            index=models.Index(fields=['session', 'status'], name='operations__session_eddfc4_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountrecount',
            index=models.Index(fields=['original_line', 'status'], name='operations__origina_a54ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecountrecount',
            index=models.Index(fields=['reference'], name='operations__referen_4dcf64_idx'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountrecount',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__gte', 0), ('counted_quantity__isnull', True), _connector='OR'), name='cycle_count_recount_counted_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountrecount',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'in_progress', 'submitted'])), fields=('original_line',), name='unique_active_cycle_count_recount_per_line'),
        ),
    ]
