# Generated by Django 5.2.16 on 2026-07-17 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_cyclecountrecount_stockmovement_cycle_count_recount_and_more'),
        ('warehouse', '0002_product_presentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerQuickTransferOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_operation_id', models.CharField(max_length=64, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scanner_quick_transfer_operations', to='warehouse.branch')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scanner_quick_transfer_destination_operations', to='warehouse.location')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_quick_transfer_operations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scanner_quick_transfer_operations', to='warehouse.product')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scanner_quick_transfer_source_operations', to='warehouse.location')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scanner_quick_transfer_operation', to='operations.stockmovement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_operation_id'], name='operations__client__0d8ed3_idx'), models.Index(fields=['branch', 'status'], name='operations__branch__7a47a3_idx'), models.Index(fields=['performed_by', 'status'], name='operations__perform_0915f3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='scanner_quick_transfer_quantity_positive')],
            },
        ),
    ]
